### ISSUE TITLE
imap sample code Can not connect to imap.gmail.com

### ISSUE THREAD

**Issue by KAZIcodes** [dinhvh/libetpan#434] opened 2023-05-28 17:36 UTC
when I run the program I get the error: 
connect: 43
could not connect to server
what is the problem ? 
for the record I changed the imap server to outlook and yahoo and it still does not work !

**Comment by InterLinked1** [comment] 2023-07-21 20:07
> when I run the program I get the error: connect: 43 could not connect to server what is the problem ? for the record I changed the imap server to outlook and yahoo and it still does not work !

Can you provide a minimally reproducible code example? It's impossible for anyone to guess what you were trying exactly.

**Comment by KAZIcodes** [comment] 2023-07-24 07:16
I did the connecting part of my project using another library and I got rid of the files when I was working with this library so I dont have them and I dont remember sorry !

**Comment by InterLinked1** [comment] 2023-07-24 10:49
> I did the connecting part of my project using another library and I got rid of the files when I was working with this library so I dont have them and I dont remember sorry !

You should close this issue then, since nobody's going to be able to reproduce it, and it was most likely user error.

**Closed as completed** 2023-11-29 07:43 UTC
